# A simple Makefile
# Alexandra Veney G00677630
# CS 262, Lab Section 201
# Lab 2

CFLAGS=-g -Wall

all: lab2_aveney2_201.c
	gcc $(CFLAGS) -o lab2_aveney2_201 lab2_aveney2_201.c -lm

clean:
	rm lab2_aveney2_201
